Import of v1.0.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -931,6 +931,8 @@ MIPCONFIG_SUPPORT_OSS
 MIPCONFIG_SUPPORT_SDLAUDIO
 MIPCONFIG_SUPPORT_OPENAL
 MIPCONFIG_SUPPORT_PORTAUDIO
+MIPCONFIG_SUPPORT_AUDIOTRACK
+MIPCONFIG_SUPPORT_AUDIORECORDER
 MIPCONFIG_GPL
 LIBOBJS
 LTLIBOBJS'
@@ -1547,6 +1549,7 @@ Optional Features:
   --enable-avcodec        Enable libavcodec support
   --disable-gsm           Disable GSM codec
   --disable-lpc           Disable LPC codec
+  --enable-android        Enable Android IO components
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2352,7 +2355,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=emiplib
- VERSION=0.17.0
+ VERSION=1.0.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2517,6 +2520,8 @@ MIPCONFIG_SUPPORT_OSS="// No support for OSS"
 MIPCONFIG_SUPPORT_SDLAUDIO="// No support for SDL audio"
 MIPCONFIG_SUPPORT_OPENAL="// No support for OpenAL"
 MIPCONFIG_SUPPORT_PORTAUDIO="// No support for PortAudio"
+MIPCONFIG_SUPPORT_AUDIOTRACK="// No support for AudioTrack output"
+MIPCONFIG_SUPPORT_AUDIORECORDER="// No support for AudioRecorder input"
 MIPCONFIG_GPL="// No GPL components will be compiled"
 
 MIPLINKLIBS="$LDFLAGS"
@@ -2524,6 +2529,7 @@ MIPINCLUDES="$CPPFLAGS"
 MIPGPL="no"
 MIPQT="no"
 MIPAVCODEC="no"
+MIPANDROID="no"
 
 if test "BLA$CXXFLAGS" = "BLA" ; then
 		CXXFLAGS="-O2 "
@@ -4909,7 +4915,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4912 "configure"' > conftest.$ac_ext
+  echo '#line 4918 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7174,11 +7180,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7177: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7183: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7181: \$? = $ac_status" >&5
+   echo "$as_me:7187: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7464,11 +7470,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7467: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7473: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7471: \$? = $ac_status" >&5
+   echo "$as_me:7477: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7568,11 +7574,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7571: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7577: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7575: \$? = $ac_status" >&5
+   echo "$as_me:7581: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9917,7 +9923,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9920 "configure"
+#line 9926 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10017,7 +10023,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10020 "configure"
+#line 10026 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12437,11 +12443,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12440: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12446: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12444: \$? = $ac_status" >&5
+   echo "$as_me:12450: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12541,11 +12547,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12550: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12548: \$? = $ac_status" >&5
+   echo "$as_me:12554: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14103,11 +14109,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14106: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14112: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14110: \$? = $ac_status" >&5
+   echo "$as_me:14116: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14207,11 +14213,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14210: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14216: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14214: \$? = $ac_status" >&5
+   echo "$as_me:14220: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16394,11 +16400,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16397: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16403: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16401: \$? = $ac_status" >&5
+   echo "$as_me:16407: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16684,11 +16690,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16687: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16693: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16691: \$? = $ac_status" >&5
+   echo "$as_me:16697: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16788,11 +16794,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16797: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16795: \$? = $ac_status" >&5
+   echo "$as_me:16801: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26086,7 +26092,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 26089: $i/$j" >&5
+    echo "configure: 26095: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -26391,7 +26397,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 26394: $i/$j" >&5
+    echo "configure: 26400: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -28159,8 +28165,139 @@ echo "${ECHO_T}$ac_cv_header_speex_speex_h" >&6; }
 
 fi
 if test $ac_cv_header_speex_speex_h = yes; then
-  MIPCONFIG_SUPPORT_SPEEX="#define MIPCONFIG_SUPPORT_SPEEX"
-			       MIPLINKLIBS="$MIPLINKLIBS -lspeex"
+
+	MIPCONFIG_SUPPORT_SPEEX="#define MIPCONFIG_SUPPORT_SPEEX"
+	MIPLINKLIBS="$MIPLINKLIBS -lspeex"
+	if test "${ac_cv_header_speex_speex_echo_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for speex/speex_echo.h" >&5
+echo $ECHO_N "checking for speex/speex_echo.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_speex_speex_echo_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_speex_speex_echo_h" >&5
+echo "${ECHO_T}$ac_cv_header_speex_speex_echo_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking speex/speex_echo.h usability" >&5
+echo $ECHO_N "checking speex/speex_echo.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <speex/speex_echo.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking speex/speex_echo.h presence" >&5
+echo $ECHO_N "checking speex/speex_echo.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <speex/speex_echo.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: speex/speex_echo.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: speex/speex_echo.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: speex/speex_echo.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: speex/speex_echo.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for speex/speex_echo.h" >&5
+echo $ECHO_N "checking for speex/speex_echo.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_speex_speex_echo_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_speex_speex_echo_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_speex_speex_echo_h" >&5
+echo "${ECHO_T}$ac_cv_header_speex_speex_echo_h" >&6; }
+
+fi
+if test $ac_cv_header_speex_speex_echo_h = yes; then
+  MIPLINKLIBS="$MIPLINKLIBS -lspeexdsp"
+fi
+
+
 fi
 
 
@@ -29126,6 +29263,19 @@ fi
 
 
 
+# Check whether --enable-android was given.
+if test "${enable_android+set}" = set; then
+  enableval=$enable_android;  if test $enableval = "yes" ; then
+	       		MIPANDROID="yes"
+	        fi
+fi
+
+
+if test $MIPANDROID = "yes" ; then
+	MIPCONFIG_SUPPORT_AUDIOTRACK="#define MIPCONFIG_SUPPORT_AUDIOTRACK"
+	MIPCONFIG_SUPPORT_AUDIORECORDER="#define MIPCONFIG_SUPPORT_AUDIORECORDER"
+fi
+
 
 if test $cross_compiling = "yes" ; then
 	cat << EOF
@@ -29385,6 +29535,8 @@ esac
 		MIPCONFIG_BIGENDIAN="#define MIPCONFIG_BIGENDIAN"
 	fi
 fi
+
+
 
 
 
@@ -30296,12 +30448,14 @@ MIPCONFIG_SUPPORT_OSS!$MIPCONFIG_SUPPORT_OSS$ac_delim
 MIPCONFIG_SUPPORT_SDLAUDIO!$MIPCONFIG_SUPPORT_SDLAUDIO$ac_delim
 MIPCONFIG_SUPPORT_OPENAL!$MIPCONFIG_SUPPORT_OPENAL$ac_delim
 MIPCONFIG_SUPPORT_PORTAUDIO!$MIPCONFIG_SUPPORT_PORTAUDIO$ac_delim
+MIPCONFIG_SUPPORT_AUDIOTRACK!$MIPCONFIG_SUPPORT_AUDIOTRACK$ac_delim
+MIPCONFIG_SUPPORT_AUDIORECORDER!$MIPCONFIG_SUPPORT_AUDIORECORDER$ac_delim
 MIPCONFIG_GPL!$MIPCONFIG_GPL$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 70; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
